<a href="https://colab.research.google.com/github/lizmosquera/HousePricePredictionKaggle/blob/master/S%2BP%20Week%202%20Lesson4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [7]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(),end="")
  print()

01234
12345
23456
34567
45678
56789


In [8]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True)
dataset=dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
  print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [13]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True)
dataset=dataset.flat_map(lambda window: window.batch(5))
dataset=dataset.map(lambda window: (window[:-1],window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [15]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True)
dataset=dataset.flat_map(lambda window: window.batch(5))
dataset=dataset.map(lambda window: (window[:-1],window[-1:]))
dataset=dataset.shuffle(buffer_size=10) #10 data what we have
for x,y in dataset:
  print(x.numpy(), y.numpy())

[4 5 6 7] [8]
[3 4 5 6] [7]
[5 6 7 8] [9]
[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]


In [16]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True)
dataset=dataset.flat_map(lambda window: window.batch(5))
dataset=dataset.map(lambda window: (window[:-1],window[-1:]))
dataset=dataset.shuffle(buffer_size=10) #10 data what we have
dataset=dataset.batch(2).prefetch(1)#size parameter =2 corresponde Yb
for x,y in dataset:
  print("x=",x.numpy())
  print("y=",y.numpy())

x= [[3 4 5 6]
 [5 6 7 8]]
y= [[7]
 [9]]
x= [[0 1 2 3]
 [2 3 4 5]]
y= [[4]
 [6]]
x= [[4 5 6 7]
 [1 2 3 4]]
y= [[8]
 [5]]


In [0]:
def windowed_dataset(series,window_size,batch_size,suffle_buffer):
  dataset=tf.data.Dataset.from_tensor_slices(series) #create a dataset
  dataset=dataset.window(window_size+1,shift=1,drop_remainder=True)#to slice the data up into the appropriate windows
  dataset=dataset.flat_map(lambda window: window.batch(window_size+1))#flatten the data out flatened into chunksin the suze of our window_size+1
  dataset=dataset.shuffle(shuffle_buffer).map(lambda window:(window[:-1],window[-1])) #shuflet it, choosing smaller number speeds
  dataset=dataset.batch(batch_size).prefetch(1)#size parameter =2 corresponde Yb
  return dataset

In [25]:

split_time=1000
time_train=time[:split_time]
x_train=series[:split_time]
time_valid=time[split_time:]
x_valid=series[split_time:]


NameError: ignored

In [26]:
#linnear regresion
window_size=20
batch_size=32
shuffle_buffer_size=1000

dataset=windowed_dataset(series,window_size,batch_size,shuffle_buffer_size)
#10=tf.keras.models.Sequential([10])
l0=tf.keras.layers.Dense(1,input_shape=[window_size])
model=tf.keras.models.Sequential([l0])
model.compile(loss="mse",optimizer=tf.keras.optimizers.SGD(lr=1e-6,momentum=0.9))
model.fit(dataset,epochs=100,verbose=0) #ignore epoch but epoch
print("layer weights {}".format(l0.get_weights()))


NameError: ignored

In [0]:
print(series([1:21])
model.predict(seriees[1:21][np.newaxis])
forecast=[]
for time in range(len(series)-window_size):
  forecast.append(model.predict(series[time:time+window_size][np.newaxis]))
forecast=forecast[split_time-window_size:]
results=np.array(frecast)[:,0,0]
tf.keras.metrics.mean_absolute_error(x_valid,results).numpy()
                                     


S+P Week 2 Lesson 4

In [28]:
!pip install tf_nightly-2.0-preview

ERROR: Could not find a version that satisfies the requirement tf_nightly-2.0-preview (from versions: none)
ERROR: No matching distribution found for tf_nightly-2.0-preview


In [29]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print (tf.__version__)

2.2.0-rc3


In [0]:
def plot_series(time,series,format="-",start=0,end=None):
  plt.plot(time[start:end],series[start:end],format)
  plt.xlabel("Time")
  plt.ylabel("Value")
  plt.grid(True)

def trend (time,slope=0);
  return slope*time

def seasonal_pattern(season_time):
  ""Just an argitraty pattern, you can chnge it if you wish""
  return np.where(season_time <0.4,np.cos(season_time*2*np.pi),1/np.exp(3*season_time))

def seasonality (time, period, amplitude=1,phase=0):
  """Repeats the same pattern at each period"""
  season_time=((time+phase)%period)/period
  return amplitude*seasonal_pattern(season_time)

def noise(time,noise_level=1,seed=none):
  